#!/usr/bin/env Rscript
suppressPackageStartupMessages({library(ggplot2); library(scales)})
a<-commandArgs(TRUE); val<-function(x){i<-match(x,a);if(is.na(i)||i==length(a))stop("Missing ",x);a[i+1]}
b<-normalizePath(val("--bundle")); o<-val("--outdir")
if(dir.exists(o)&&length(list.files(o)))stop("OUTDIR must be new or empty")
for(d in c("figures/main_candidates","figures/supplement_candidates","figure_source","provenance"))dir.create(file.path(o,d),recursive=TRUE)
rd<-function(...)read.delim(file.path(b,...),check.names=FALSE,stringsAsFactors=FALSE,na.strings="NA")
wr<-function(x,n)write.table(x,file.path(o,"figure_source",n),sep="\t",quote=FALSE,row.names=FALSE,na="NA")
sv<-function(f,n,p,w=10,h=6){s<-file.path(o,"figures",f,n);ggsave(paste0(s,".pdf"),plot=p,width=w,height=h,device=cairo_pdf);ggsave(paste0(s,".png"),plot=p,width=w,height=h,dpi=320,bg="white")}
pl<-c(kraken2_bracken="Kraken2 + Bracken",metaphlan4="MetaPhlAn 4"); pc<-c("Kraken2 + Bracken"="#D55E00","MetaPhlAn 4"="#0072B2")
dec<-function(x){x$Profiler<-factor(pl[x$profiler],levels=pl);x$Experiment<-factor(c(community="Community",independent="Independent")[x$analysis_population],levels=c("Community","Independent"));x$Cohort<-factor(tools::toTitleCase(x$cohort),levels=c("Feng","Zeller","Yachida"));x}
pri<-function(x){z<-x$q_threshold==.05;if("analysis_scope"%in%names(x))z<-z&x$analysis_scope=="pooled_primary";x[z,,drop=FALSE]}
th<-theme_bw(10)+theme(panel.grid.minor=element_blank(),panel.grid.major=element_line(linewidth=.25,color="grey88"),legend.position="bottom",strip.background=element_rect(fill="grey94"),strip.text=element_text(face="bold"),plot.title.position="plot")
cs<-scale_color_manual(values=pc,breaks=names(pc)); fs<-scale_fill_manual(values=pc,breaks=names(pc))
xs<-function()scale_x_log10(breaks=c(.001,.005,.01,.05,.1,.5,1,5),labels=label_number(accuracy=.001))
art<-dec(pri(rd("reports","artificial","tables","artificial_biomarker_summary.tsv")))
mdd<-dec(pri(rd("reports","artificial","tables","minimum_detectable_dose.tsv")))
dis<-dec(rd("reports","disease","figure_source","disease_biomarker_propagation.tsv"));dis<-dis[dis$q_threshold==.05,]
if(all(c("baseline_bystander_biomarkers","bystander_retention_rate")%in%names(dis))){dis$baseline_biomarkers<-dis$baseline_bystander_biomarkers;dis$baseline_retention_rate<-dis$bystander_retention_rate}
lnk<-dec(pri(rd("reports","calibration_linkage","figure_source","calibration_biomarker_linkage.tsv")))
am<-unique(dis[c("target_label","target_alias")]);am<-am[!duplicated(am$target_label),];am$Species<-vapply(strsplit(am$target_alias," "),function(z)paste0(substr(z[1],1,1),". ",z[2]),"")

# Sensitivity heatmap
mdd<-merge(mdd,am,by="target_label",all.x=TRUE,sort=FALSE);mdd$dose<-as.numeric(mdd$minimum_sustained_detected_nominal_percent);dl<-sort(unique(mdd$dose));mdd$Dose<-factor(mdd$dose,dl,paste0(format(dl,trim=TRUE),"%"));mdd$Species<-factor(mdd$Species,am$Species[order(am$target_label)]);wr(mdd,"minimum_detectable_dose.tsv")
p<-ggplot(mdd,aes(Species,Profiler,fill=Dose))+geom_tile(color="white",linewidth=.5)+geom_text(aes(label=Dose),size=2.5)+facet_grid(Experiment~Cohort,drop=TRUE)+scale_fill_viridis_d(option="C",direction=-1,drop=FALSE)+labs(x="Implanted species",y=NULL,title="Detection sensitivity depends on species, profiler, and perturbation design",subtitle="Minimum sustained detectable fraction; pooled paired models, BH q <= 0.05",caption="Lower percentages indicate greater analytical sensitivity.")+th+theme(axis.text.x=element_text(angle=42,hjust=1));sv("main_candidates","figure_01_detection_sensitivity",p,10.5,6.1)

# Report burden per perturbation context. This is available from the sealed
# report and avoids requiring the very large feature-level model table merely
# to construct a denominator. It is a burden measure, not a false-positive rate.
art$dose<-as.numeric(art$dose_percent_nominal);art$off_target_calls_per_context<-as.numeric(art$context_sum_off_target_calls)/as.numeric(art$contexts);art$recall<-100*as.numeric(art$target_recall);art$precision<-100*as.numeric(art$mean_precision);wr(art,"artificial_recovery_specificity.tsv")
p<-ggplot(art,aes(dose,off_target_calls_per_context,color=Profiler,group=Profiler))+geom_line()+geom_point(size=1.8)+facet_grid(Experiment~Cohort,drop=TRUE)+xs()+scale_y_continuous(trans=pseudo_log_trans(base=10,sigma=.01))+cs+labs(x="Implanted target fraction (%)",y="Off-target significant calls per context",title="Artificial perturbations generate profiler-specific off-target discoveries",subtitle="Mean off-target calls per implanted-species context; BH q <= 0.05",caption="This is discovery burden, not a feature-normalized false-positive rate.")+th;sv("main_candidates","figure_02_off_target_discovery_rate",p,10,6.4)
for(z in list(list("figure_s01_target_recall","Ground-truth target recovery","Target recall",art$recall),list("figure_s02_target_precision","Precision of artificial-biomarker recovery","Positive predictive value",art$precision))){art$yy<-z[[4]];p<-ggplot(art,aes(dose,yy,color=Profiler,group=Profiler))+geom_line()+geom_point()+facet_grid(Experiment~Cohort,drop=TRUE)+xs()+scale_y_continuous(trans=if(z[[1]]=="figure_s02_target_precision")pseudo_log_trans(base=10,sigma=.01)else "identity",limits=c(0,100),labels=label_percent(scale=1))+cs+labs(x="Implanted target fraction (%)",y=z[[3]],title=z[[2]],subtitle="Pooled across ten implanted species; BH q <= 0.05")+th;sv("supplement_candidates",z[[1]],p,10,6.2)}

# Baseline denominator and retention
base<-unique(dis[c("cohort","Cohort","analysis_population","Experiment","profiler","Profiler","contrast","baseline_biomarkers")]);base<-base[base$contrast=="CRC_vs_Control",];wr(base,"baseline_disease_biomarker_counts.tsv")
p<-ggplot(base,aes(Profiler,baseline_biomarkers,color=Profiler))+geom_segment(aes(xend=Profiler,y=0,yend=baseline_biomarkers),color="grey75")+geom_point(size=3)+geom_text(aes(label=baseline_biomarkers),nudge_y=.1)+facet_grid(Experiment~Cohort,drop=TRUE,scales="free_y")+scale_y_continuous(trans=log1p_trans(),breaks=c(0,1,2,4,10,25,50,100,250))+cs+guides(color="none")+labs(x=NULL,y="Baseline CRC biomarkers (log1p)",title="The native disease-signature denominator varies substantially",subtitle="CRC versus Control at BH q <= 0.05; labels show exact counts")+th;sv("main_candidates","figure_03a_baseline_disease_biomarkers",p,9,6.3)
dis$dose<-100*as.numeric(dis$spike_fraction_target);dis$retention<-as.numeric(dis$baseline_retention_rate);def<-dis[dis$contrast=="CRC_vs_Control"&is.finite(dis$retention),]
keys<-c("cohort","Cohort","analysis_population","Experiment","profiler","Profiler","dose");g<-split(def,interaction(def[keys],drop=TRUE));ret<-do.call(rbind,lapply(g,function(x)data.frame(x[1,keys],n_targets=nrow(x),median=median(x$retention),q25=quantile(x$retention,.25),q75=quantile(x$retention,.75),check.names=FALSE)));wr(ret,"disease_retention_summary.tsv")
p<-ggplot(ret,aes(dose,median,color=Profiler,fill=Profiler,group=Profiler))+geom_ribbon(aes(ymin=q25,ymax=q75),alpha=.14,color=NA)+geom_line()+geom_point()+facet_grid(Experiment~Cohort,drop=TRUE)+xs()+scale_y_continuous(limits=c(0,1),labels=label_percent())+cs+fs+labs(x="Implanted target fraction (%)",y="Baseline CRC biomarkers retained",title="Controlled perturbations can erode native CRC biomarker signatures",subtitle="Median and IQR across ten implanted species; CRC versus Control, BH q <= 0.05",caption="Zero-baseline contexts are undefined, not zero; baseline counts appear in Figure 3a.")+th;sv("main_candidates","figure_03b_disease_biomarker_retention",p,10,6.4)

# Target-trajectory linkage avoids treating repeated doses as independent.
cal<-unique(lnk[c("cohort","analysis_population","target_label","profiler","spike_fraction_target","median_response_ratio")]);cal$spike_fraction_target<-signif(as.numeric(cal$spike_fraction_target),10);dd<-dis[dis$contrast=="CRC_vs_Control",c("cohort","analysis_population","target_label","profiler","spike_fraction_target","biomarker_set_jaccard_vs_baseline")];dd$spike_fraction_target<-signif(as.numeric(dd$spike_fraction_target),10);j<-merge(dd,cal,by=c("cohort","analysis_population","target_label","profiler","spike_fraction_target"));j$calibration_error<-abs(log2(as.numeric(j$median_response_ratio)));j$distortion<-1-as.numeric(j$biomarker_set_jaccard_vs_baseline);j<-j[is.finite(j$calibration_error)&is.finite(j$distortion),];tk<-c("cohort","analysis_population","target_label","profiler");tr<-aggregate(j[c("calibration_error","distortion")],j[tk],median);tr<-dec(merge(tr,am,by="target_label",all.x=TRUE));wr(j,"linkage_dose_level.tsv");wr(tr,"linkage_target_trajectories.tsv")
ck<-c("cohort","Cohort","analysis_population","Experiment","profiler","Profiler");cg<-split(tr,interaction(tr[ck],drop=TRUE));cr<-do.call(rbind,lapply(cg,function(x){q<-suppressWarnings(cor.test(x$calibration_error,x$distortion,method="spearman",exact=FALSE));data.frame(x[1,ck],n=nrow(x),rho=unname(q$estimate),p=q$p.value)}));wr(cr,"linkage_spearman.tsv")
p<-ggplot(tr,aes(calibration_error,distortion,color=Profiler))+geom_point(size=2.2,alpha=.8)+geom_smooth(method="lm",se=FALSE,linetype=2,linewidth=.7)+facet_grid(Experiment~Cohort,drop=TRUE)+scale_y_continuous(labels=label_percent())+coord_cartesian(ylim=c(0,1))+cs+labs(x="Median absolute calibration error |log2(response ratio)|",y="Median CRC-signature distortion (1 - Jaccard)",title="Does miscalibration predict downstream biomarker instability?",subtitle="Each point is one implanted-species trajectory; dashed fits are descriptive",caption="Exploratory mechanistic linkage, not a confirmatory causal test.")+th;sv("main_candidates","figure_04_calibration_vs_signature_distortion",p,10,6.5)

diag<-data.frame(metric=c("status","cohorts","defined_CRC_rows","target_trajectories","zero_baseline_Adenoma_rows"),value=c("DEVELOPMENT_ONLY",length(unique(art$cohort)),nrow(def),nrow(tr),sum(dis$contrast=="Adenoma_vs_Control"&dis$baseline_biomarkers==0)));wr(diag,"diagnostics.tsv")
writeLines(c("status=DEVELOPMENT_ONLY","use_for_manuscript=NO","reason=figure_and_analysis_development"),file.path(o,"DEVELOPMENT_ONLY.txt"))
writeLines(c("# Development figure candidates","","Three-cohort development outputs: layouts and analyses remain provisional until the definitive cohort runs are sealed.","","Main: sensitivity; off-target discovery burden; baseline CRC denominator; CRC retention; exploratory calibration-to-distortion linkage.","","Off-target calls per context are a burden measure, not a feature-normalized false-positive rate."),file.path(o,"FIGURE_GUIDE.md"))
files<-list.files(o,recursive=TRUE,full.names=TRUE);system2("sha256sum",files,stdout=file.path(o,"provenance","figure_candidates.sha256"));writeLines("completion=PASS",file.path(o,"SUCCESS"));message("[PASS] ",normalizePath(o))
