#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

usage() {
  cat <<'EOF'
Usage:
  configure_spike_workflow.sh \
    --site-env config/dataset.env \
    --work-dir work/dataset \
    --reference-dir references/genomes \
    [--samples-tsv /path/to/cleaned_samples.tsv]

Creates, without modifying tracked files:
  WORK_DIR/spike_panel.local.tsv
  WORK_DIR/spikein.env

The site environment must define UPSTREAM_SIF. The optional samples table must
have sample_id, R1, and R2 as its first three tab-separated columns. It may be
omitted while generating the shared spike pools and supplied later per batch.
EOF
}

SITE_ENV=""
WORK_DIR=""
REFERENCE_DIR=""
SAMPLES_TSV_ARG=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --site-env) SITE_ENV="$2"; shift 2 ;;
    --work-dir) WORK_DIR="$2"; shift 2 ;;
    --reference-dir) REFERENCE_DIR="$2"; shift 2 ;;
    --samples-tsv) SAMPLES_TSV_ARG="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "[ERROR] Unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

[[ -n "$SITE_ENV" && -n "$WORK_DIR" && -n "$REFERENCE_DIR" ]] || {
  usage
  exit 2
}
[[ -f "$SITE_ENV" ]] || { echo "[ERROR] Missing site environment: $SITE_ENV" >&2; exit 1; }

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"

# shellcheck disable=SC1090
source "$SITE_ENV"
: "${UPSTREAM_SIF:?UPSTREAM_SIF must be defined in the site environment}"
[[ -s "$UPSTREAM_SIF" ]] || { echo "[ERROR] Missing/empty image: $UPSTREAM_SIF" >&2; exit 1; }

mkdir -p "$WORK_DIR"
WORK_DIR="$(cd "$WORK_DIR" && pwd)"
REFERENCE_DIR="$(cd "$REFERENCE_DIR" && pwd)"
SOURCE_PANEL="$REPO_ROOT/spikes/spike_panel.tsv"
LOCAL_PANEL="$WORK_DIR/spike_panel.local.tsv"
OUTPUT_ENV="$WORK_DIR/spikein.env"
POOLS_DIR="$WORK_DIR/spike_pools_readlen100_cov2000"

[[ -s "$SOURCE_PANEL" ]] || { echo "[ERROR] Missing panel: $SOURCE_PANEL" >&2; exit 1; }

awk -v root="$REFERENCE_DIR" '
  BEGIN { FS=OFS="\t" }
  NR == 1 { print; next }
  { $4=root "/" $1 ".fa"; print }
' "$SOURCE_PANEL" > "$LOCAL_PANEL"

missing=0
while IFS=$'\t' read -r label _taxon _assembly fasta _rest; do
  [[ "$label" == "label" ]] && continue
  if [[ ! -s "$fasta" ]]; then
    echo "[ERROR] Missing/empty reference for $label: $fasta" >&2
    missing=1
  fi
done < "$LOCAL_PANEL"
(( missing == 0 )) || exit 1

{
  printf '# Generated by %s; local paths only. Do not commit.\n' "${BASH_SOURCE[0]}"
  printf 'IMG=%q\n' "$UPSTREAM_SIF"
  printf 'BIND=%q\n' "$REPO_ROOT:$REPO_ROOT"
  printf 'WORK=%q\n' "$WORK_DIR"
  if [[ -n "$SAMPLES_TSV_ARG" ]]; then
    [[ -s "$SAMPLES_TSV_ARG" ]] || { echo "[ERROR] Missing/empty samples table: $SAMPLES_TSV_ARG" >&2; exit 1; }
    printf 'SAMPLES_TSV=%q\n' "$(cd "$(dirname "$SAMPLES_TSV_ARG")" && pwd)/$(basename "$SAMPLES_TSV_ARG")"
  else
    printf '%s\n' 'SAMPLES_TSV=${SAMPLES_TSV:-}'
  fi
  printf 'SPIKE_PANEL=%q\n' "$LOCAL_PANEL"
  printf 'POOLS_DIR=%q\n' "$POOLS_DIR"
  cat <<'EOF'
READLEN=100
COVERAGE=2000
FRAGMEAN=350
FRAGSD=10
THREADS=8
INDEPENDENT_FRACTIONS=0.0001,0.0005,0.001,0.005,0.01,0.05
COMMUNITY_FRACTIONS=0.0001,0.0005,0.001,0.005,0.01,0.05,0.10
SEED_BASE=13
MAX_CONCURRENT=5
SAMPLING_MODE=legacy
MAMBA_ENV=taxonomic_tools
EOF
} > "$OUTPUT_ENV"

echo "[PASS] Local spike configuration created"
echo "[OK] Panel: $LOCAL_PANEL"
echo "[OK] Environment: $OUTPUT_ENV"
echo "[OK] Pools: $POOLS_DIR"
if [[ -z "$SAMPLES_TSV_ARG" ]]; then
  echo "[INFO] SAMPLES_TSV is intentionally deferred until a cleaned-read batch is available."
fi
