#!/usr/bin/env bash
set -euo pipefail

usage(){
  cat <<'EOF'
Usage:
  make_samples_spiked_tsv.sh --in samples.tsv --parts logs/spiked_manifest_parts --out samples_spiked.tsv

Combines:
  1) the original samples.tsv (header + original rows)
  2) all per-sample manifest parts generated by the spike array job

The parts directory should contain one or more .tsv files, each with rows
matching the original column structure.
EOF
}

IN=""; PARTS=""; OUT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --in) IN="$2"; shift 2;;
    --parts) PARTS="$2"; shift 2;;
    --out) OUT="$2"; shift 2;;
    -h|--help) usage; exit 0;;
    *) echo "[ERROR] Unknown arg: $1" >&2; usage; exit 2;;
  esac
done

[[ -n "$IN" && -n "$PARTS" && -n "$OUT" ]] || { usage; exit 2; }
[[ -f "$IN" ]] || { echo "[ERROR] Missing: $IN" >&2; exit 1; }
[[ -d "$PARTS" ]] || { echo "[ERROR] Missing dir: $PARTS" >&2; exit 1; }

head -n 1 "$IN" > "$OUT"
# keep originals
if [[ $(wc -l < "$IN") -gt 1 ]]; then
  tail -n +2 "$IN" >> "$OUT"
fi

find "$PARTS" -type f -name "*.tsv" | sort | while read -r f; do
  cat "$f" >> "$OUT"
done

echo "[OK] Wrote $OUT"
