#!/usr/bin/env Rscript

# Regenerate manuscript Figures 2--5 from analysis outputs. Figure 1 is a
# non-statistical study-design schematic and is maintained with the manuscript
# source. Figures 6 and 7 are generated by their dedicated analysis scripts.

suppressPackageStartupMessages({
  library(optparse)
  library(cowplot)
  library(ggplot2)
  library(png)
})

options <- list(
  make_option("--project-root", default = "."),
  make_option("--run-dir", default = "RUNS_publication_original_unpaired_q010"),
  make_option("--metadata", default = "metadata_w_study.tsv"),
  make_option("--kraken", default = "kraken2_bracken_merged_unspecified.csv"),
  make_option("--metaphlan", default = "metaphlan4_merged_unspecified.csv"),
  make_option("--dpi", type = "integer", default = 450,
              help = "PNG resolution for final composites [default %default]"),
  make_option(
    "--rerun-panels", type = "logical", default = TRUE,
    help = "Regenerate source panels before assembly [default %default]"
  )
)
opt <- parse_args(OptionParser(option_list = options))
root <- normalizePath(opt$`project-root`, mustWork = TRUE)
run_dir <- if (grepl("^/", opt$`run-dir`)) opt$`run-dir` else file.path(root, opt$`run-dir`)
scripts <- file.path(root, "scripts")
outdir <- file.path(run_dir, "manuscript_figures", "current")
panels <- file.path(outdir, "source_panels")
dir.create(panels, recursive = TRUE, showWarnings = FALSE)

abs_path <- function(x) if (grepl("^/", x)) x else file.path(root, x)
run_r <- function(script, args) {
  path <- file.path(scripts, script)
  if (!file.exists(path)) stop("Missing script: ", path, call. = FALSE)
  status <- system2(file.path(R.home("bin"), "Rscript"), c(path, args))
  if (status != 0) stop("Plot script failed: ", script, call. = FALSE)
}
arg <- function(name, value) c(paste0("--", name), value)

d2 <- file.path(panels, "fig2_baseline")
d2_supp <- file.path(panels, "supp_baseline_all_10_targets")
d3a <- file.path(panels, "fig3_independent")
d3b <- file.path(panels, "fig3_fnuc")
d4 <- file.path(panels, "fig4_recoverability")
d5a <- file.path(panels, "fig5_community_abundance")
d5b <- file.path(panels, "fig5_community_da")
for (d in c(d2, d2_supp, d3a, d3b, d4, d5a, d5b)) dir.create(d, recursive = TRUE, showWarnings = FALSE)

if (isTRUE(opt$`rerun-panels`)) {
  run_r("1st_panel_plot_manuscript_tool_discordance.R", c(
    arg("indir", file.path(run_dir, "spike_metrics")),
    arg("outdir", d2),
    arg("spike-labels", "Bfrag,Fnuc,Pmic,Pint"),
    arg("metadata-input", abs_path(opt$metadata)),
    arg("metadata-sample-col", "sample_id"),
    arg("metadata-condition-col", "Target_Condition"),
    arg("metadata-study-col", "Study")
  ))
  run_r("1st_panel_plot_manuscript_tool_discordance.R", c(
    arg("indir", file.path(run_dir, "spike_metrics")),
    arg("outdir", d2_supp),
    arg("spike-labels", "Bfrag,Csym,Dpne,Fnuc,Hhat,Pmic,Pana,Psto,Porp,Pint"),
    arg("metadata-input", abs_path(opt$metadata)),
    arg("metadata-sample-col", "sample_id"),
    arg("metadata-condition-col", "Target_Condition"),
    arg("metadata-study-col", "Study"),
    arg("taxa-per-row", "10"),
    arg("width", "18"),
    arg("height", "9")
  ))
  run_r("plot_manuscript_independent_spike_overview.R", c(
    arg("indir", file.path(run_dir, "spike_metrics")), arg("outdir", d3a),
    arg("spike-labels", "Bfrag,Csym,Dpne,Fnuc,Hhat,Pmic,Pana,Psto,Porp,Pint"),
    arg("sort-labels-by", "taxon")
  ))
  run_r("plot_manuscript_fnuc_case_study_panel.R", c(
    arg("indir", file.path(run_dir, "spike_metrics")),
    arg("metadata-input", abs_path(opt$metadata)),
    arg("kraken-input", abs_path(opt$kraken)),
    arg("metaphlan-input", abs_path(opt$metaphlan)),
    arg("outdir", d3b), arg("spike-label", "Fnuc")
  ))
  run_r("plot_manuscript_crc_biomarker_recoverability_compact.R", c(
    arg("summary-dir", file.path(run_dir, "species_driver_and_thresholds")),
    arg("outdir", d4), arg("focus-fraction", "0.0001"),
    arg("spike-label-order", "Bfrag,Csym,Dpne,Fnuc,Hhat,Pmic,Pana,Psto,Porp,Pint")
  ))
  run_r("plot_manuscript_community_spike_concordance.R", c(
    # The plotting script selects community rows itself. Use the combined table:
    # the community-only compatibility export lacks fields required by this plot.
    arg("input-file", file.path(run_dir, "spike_metrics", "target_member_errors_with_condition.csv")),
    arg("outdir", d5a), arg("community-size", "10"),
    arg("main-effective-fractions", "0.00001,0.00005,0.0001,0.0005,0.001"),
    arg("spike-label-order", "Bfrag,Csym,Dpne,Fnuc,Hhat,Pmic,Pana,Psto,Porp,Pint")
  ))
  run_r("plot_manuscript_community_DA_recovery.R", c(
    arg("indir", file.path(run_dir, "maaslin_spike")), arg("outdir", d5b),
    arg("community-size", "10"),
    arg("main-effective-fractions", "0.00001,0.00005,0.0001,0.0005,0.001"),
    arg("spike-label-order", "Bfrag,Csym,Dpne,Fnuc,Hhat,Pmic,Pana,Psto,Porp,Pint")
  ))
} else {
  message("[INFO] Reusing existing source panels in: ", panels)
}

find_panel <- function(dir, stems) {
  # Composite source plots were designed and validated on their own large
  # canvases. Import the high-resolution panel PNGs so text, legends, margins,
  # and facet strips scale together when panels are assembled. Importing the
  # native ggplot objects on a smaller composite canvas leaves point-size text
  # unchanged and can crush or clip the plotting regions.
  candidates <- unlist(lapply(stems, function(s) file.path(dir, paste0(s, c(".png", ".pdf", ".rds")))))
  hit <- candidates[file.exists(candidates)]
  if (!length(hit)) stop("Missing generated panel in ", dir, ": ", paste(stems, collapse = ", "))
  hit[[1]]
}
read_plot <- function(path) {
  if (tolower(tools::file_ext(path)) == "rds") {
    return(readRDS(path))
  }
  if (tolower(tools::file_ext(path)) == "pdf") {
    if (!requireNamespace("pdftools", quietly = TRUE)) stop("Package pdftools is required to import PDF-only panels.")
    bitmap <- pdftools::pdf_render_page(path, page = 1, dpi = 300, numeric = TRUE)
    if (max(bitmap) > 1) bitmap <- bitmap / 255
    tmp <- tempfile(fileext = ".png")
    png::writePNG(bitmap[, , seq_len(min(3, dim(bitmap)[3])), drop = FALSE], tmp)
    path <- tmp
  }
  image <- png::readPNG(path)
  grob <- grid::rasterGrob(
    image, x = 0.5, y = 0.5,
    width = grid::unit(1, "npc"), height = grid::unit(1, "npc"),
    interpolate = TRUE
  )
  cowplot::ggdraw() + cowplot::draw_grob(grob)
}
validate_nonblank_png <- function(path) {
  image <- png::readPNG(path)
  rgb <- if (length(dim(image)) == 3L) image[, , seq_len(min(3L, dim(image)[3])), drop = FALSE] else image
  nonwhite_fraction <- mean(rgb < 0.985, na.rm = TRUE)
  dynamic_range <- diff(range(rgb, finite = TRUE))
  if (!is.finite(nonwhite_fraction) || nonwhite_fraction < 0.001 ||
      !is.finite(dynamic_range) || dynamic_range < 0.02) {
    stop(
      "Generated composite is effectively blank: ", path,
      " (non-white fraction=", signif(nonwhite_fraction, 3),
      ", range=", signif(dynamic_range, 3), ")",
      call. = FALSE
    )
  }
  message(
    "[OK] Non-blank composite: ", basename(path),
    " (non-white fraction=", signif(nonwhite_fraction, 3), ")"
  )
}
save <- function(plot, stem, width, height) {
  ggsave(file.path(outdir, paste0(stem, ".pdf")), plot, width = width, height = height, device = cairo_pdf, bg = "white")
  png_path <- file.path(outdir, paste0(stem, ".png"))
  ggsave(png_path, plot, width = width, height = height, dpi = opt$dpi, bg = "white")
  validate_nonblank_png(png_path)
}

fig2 <- read_plot(find_panel(d2, "manuscript_full_baseline_discordance_panel"))
save(fig2, "Fig2_baseline_profiler_discordance", 12.2, 8.8)

fig2_supp <- read_plot(find_panel(d2_supp, "manuscript_full_baseline_discordance_panel"))
save(fig2_supp, "Supplementary_Fig_B2_baseline_all_10_targets", 18, 9)

fig3_lower <- plot_grid(
  read_plot(find_panel(d3a, "panel_B_bias_variability_dotplots_naturestyle")),
  read_plot(find_panel(d3b, c(
    "panelC_recovery_classes_lowspikes_Fnuc",
    "panelB_recovery_classes_lowspikes_Fnuc"
  ))),
  nrow = 1,
  rel_widths = c(1.85, 1),
  align = "h",
  axis = "tb"
)
fig3 <- plot_grid(
  read_plot(find_panel(d3a, "panel_A_good_recovery_dumbbell_naturestyle")),
  fig3_lower,
  ncol = 1,
  rel_heights = c(1, 1.12)
)
save(fig3, "Fig3_independent_spike_recovery", 15.2, 10.6)

fig4 <- plot_grid(
  read_plot(find_panel(d4, c(
    "panel_A_crc_biomarker_thresholds_heatmap_naturestyle",
    "panel_A_crc_biomarker_thresholds_dumbbell_naturestyle"
  ))),
  read_plot(find_panel(d4, "panel_B_biomarker_outcome_vs_intuitive_drivers_with_trends_naturestyle")),
  read_plot(find_panel(d4, "panel_C_intuitive_association_dot_summary_naturestyle")),
  ncol = 1, rel_heights = c(1, 1.1, 0.7)
)
save(fig4, "Fig4_biomarker_recoverability", 12.2, 18.2)

fig5 <- plot_grid(
  read_plot(find_panel(d5a, "panel_A_independent_vs_community_good_recovery_dumbbell")),
  read_plot(find_panel(d5a, "panel_B_community_good_recovery_dumbbell_main_effective_fractions")),
  read_plot(find_panel(d5b, "panel_B_community_target_DA_detection_main_effective_fractions")),
  ncol = 1, rel_heights = c(1, 1, 1.05)
)
save(fig5, "Fig5_community_spike_recovery_and_DA", 13.5, 18.6)

writeLines(c(
  "Current manuscript figure mapping",
  "Figure 1: study-design schematic in manuscript source (no statistical analysis)",
  "Figure 2: baseline profiler discordance",
  "Supplementary Figure B2: baseline profiler discordance for all 10 targets",
  "Figure 3: independent spike recovery",
  "Figure 4: biomarker recoverability",
  "Figure 5: community spike recovery and differential abundance",
  "Figures 6 and 7: generated by dedicated scripts in the main runner"
), file.path(outdir, "FIGURE_MAPPING.txt"))
